import { chromium } from '../../../apps/web/node_modules/playwright/index.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';

/** Exercise conversation review and lifecycle controls in an isolated real Web Profile. */
export async function verifyBrowser(home, result) {
    const browser = await chromium.launch({ channel: 'chrome', headless: true });
    let page;
    try {
        page = await browser.newPage({ locale: 'zh-CN', viewport: { width: 1440, height: 1000 } });
        page.setDefaultTimeout(15000);
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.goto(result.url);
        const next = page.getByRole('button', { name: /^(继续|稍后配置|开始使用|完成)$/ }).first();
        await next.waitFor();
        for (let i = 0; i < 8; i++) {
            await next.click();
            await page.waitForTimeout(600);
            if (!(await next.isVisible())) break;
        }
        const history = page.getByRole('region', { name: '插件规范验收店 · 智能经营', exact: true });
        const row = () => history.locator(`[data-zlm-session="${result.session}"]`);
        const conversationToggle = history.getByRole('button', { name: '插件规范验收店 · 智能经营', exact: true });
        const newChat = history.getByRole('button', { name: '插件规范验收店 · 新建对话', exact: true });
        const expandConversations = async () => {
            await conversationToggle.waitFor();
            if (await conversationToggle.getAttribute('aria-expanded') === 'false') await conversationToggle.click();
        };
        await conversationToggle.waitFor();
        assert.equal(await conversationToggle.getAttribute('aria-expanded'), 'false');
        assert.equal(await row().isVisible(), false);
        assert.equal(await history.getByRole('combobox', { includeHidden: true }).count(), 0);
        assert.equal((await newChat.innerText()).trim(), '');
        const shopDisclosure = page.locator('details').filter({ has: page.locator('summary[aria-label="插件规范验收店"]') }).first();
        await shopDisclosure.locator('summary').first().click();
        assert.equal(await history.isVisible(), false);
        await shopDisclosure.locator('summary').first().click();
        await expandConversations();
        await row().waitFor();
        assert.equal(await conversationToggle.getAttribute('aria-expanded'), 'true');
        await conversationToggle.click();
        assert.equal(await row().isVisible(), false);
        await expandConversations();
        const openHistory = async name => {
            await history.getByRole('button', { name: '插件规范验收店 · 对话管理', exact: true }).press('Enter');
            await page.getByRole('menuitem', { name, exact: true }).click();
        };
        const closeHistory = () => page.getByRole('dialog').getByRole('button', { name: '关闭', exact: true }).click();
        await row().click({ button: 'right' });
        const rowHeight = await row().evaluate(el => el.getBoundingClientRect().height);
        assert(rowHeight < 50, 'Opening actions must not expand the conversation row');
        await page.getByRole('menuitem', { name: '置顶', exact: true }).click();
        await row().getByRole('button').first().click();
        const draft = page.locator(`[data-zlm-turn-reviews] [data-zlm-review="${result.draft}"]`);
        const entryChange = page.locator(`[data-zlm-turn-reviews] [data-zlm-review="${result.proposals.find(p => p.type === 'entry').id}"]`);
        const rulesChange = page.locator(`[data-zlm-turn-reviews] [data-zlm-review="${result.proposals.find(p => p.type === 'rules').id}"]`);
        await draft.getByRole('button', { name: '确认入账', exact: true }).waitFor();
        await entryChange.getByRole('button', { name: '确认修改', exact: true }).waitFor();
        await rulesChange.getByRole('button', { name: '确认修改', exact: true }).waitFor();
        assert.equal(await page.getByRole('heading', { name: '经营总览', exact: true }).count(), 0);
        const out = fileURLToPath(new URL('../evidence/audit/', import.meta.url));
        await mkdir(out, { recursive: true });
        await draft.scrollIntoViewIfNeeded();
        await page.screenshot({ path: join(out, 'conversation-review-desktop.png'), fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.waitForFunction(() => document.querySelector('[data-zlm-turn-reviews] [data-zlm-review]')?.getBoundingClientRect().width > 200);
        await draft.scrollIntoViewIfNeeded();
        await page.screenshot({ path: join(out, 'conversation-review-mobile.png'), fullPage: true });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
        const bounds = await draft.boundingBox();
        assert(bounds && bounds.width <= 390 && bounds.width > 200, 'Inline review must fit mobile');
        await draft.getByRole('button', { name: '确认入账', exact: true }).click();
        await draft.getByText('已入账', { exact: true }).waitFor();
        await page.setViewportSize({ width: 1440, height: 1000 });
        await entryChange.getByRole('button', { name: '确认修改', exact: true }).click();
        await entryChange.getByText('已生效', { exact: true }).waitFor();
        await rulesChange.getByRole('button', { name: '确认修改', exact: true }).click();
        await rulesChange.getByText('已生效', { exact: true }).waitFor();
        console.log('Inline entry and entry/rule changes confirmed in chat.');
        const db = new DatabaseSync(join(home, 'profiles/zlm-audit/zhuanleme/ledger.sqlite'), { readOnly: true });
        const persisted = () => ({ entries: db.prepare('SELECT * FROM entries ORDER BY id').all(), rules: db.prepare('SELECT * FROM rules ORDER BY seq').all(), audit: db.prepare('SELECT * FROM audit ORDER BY seq').all() });
        try {
            const entry = db.prepare('SELECT * FROM entries WHERE id=?').get(result.original);
            assert.equal(JSON.parse(entry.data).amount, 82000);
            assert.equal(entry.version, 2);
            assert.equal(db.prepare('SELECT status FROM entries WHERE id=?').get(result.draft).status, 'posted');
            assert.equal(JSON.parse(db.prepare('SELECT data FROM rules WHERE shop=?').get(result.shop).data).value, 300000);
            assert.equal(db.prepare("SELECT COUNT(*) AS n FROM proposals WHERE shop=? AND status='applied'").get(result.shop).n, 2);
            const before = persisted();
            await page.reload();
            await expandConversations();
            // Opening the stored session restores cards with their authoritative final state.
            if (!(await draft.isVisible())) await row().getByRole('button').first().click();
            await draft.getByText('已入账', { exact: true }).waitFor();
            assert.equal(await draft.getByRole('button', { name: '确认入账', exact: true }).count(), 0);
            if (await row().getByRole('button', { name: /对话操作/ }).count()) await row().getByRole('button', { name: /对话操作/ }).click(); else await row().click({button:'right'});
            await page.getByRole('menuitem', { name: '归档', exact: true }).click();
            await row().waitFor({ state: 'detached' });
            await openHistory('已归档对话');
            if (await row().getByRole('button', { name: /对话操作/ }).count()) await row().getByRole('button', { name: /对话操作/ }).click(); else await row().click({button:'right'});
            await page.getByRole('menuitem', { name: '取消归档', exact: true }).click();
            await closeHistory();
            await row().getByRole('button').first().click();
            if (await row().getByRole('button', { name: /对话操作/ }).count()) await row().getByRole('button', { name: /对话操作/ }).click(); else await row().click({button:'right'});
            await page.getByRole('menuitem', { name: '移至已删除', exact: true }).click();
            await page.getByRole('menuitem', { name: '确认移至已删除', exact: true }).click();
            await row().waitFor({ state: 'detached' });
            await page.reload();
            await expandConversations();
            await openHistory('已删除对话');
            if (await row().getByRole('button', { name: /对话操作/ }).count()) await row().getByRole('button', { name: /对话操作/ }).click(); else await row().click({button:'right'});
            await page.screenshot({ path: join(out, 'conversation-deleted-desktop.png'), fullPage: true });
            await page.getByRole('menuitem', { name: '恢复对话', exact: true }).click();
            await closeHistory();
            await row().getByRole('button').first().click();
            await draft.getByText('已入账', { exact: true }).waitFor();
            assert.deepEqual(persisted(), before, 'Conversation lifecycle must not change shop entries, rules, or audit');
            await page.reload();
            await page.getByRole('button', { name:'插件规范验收店 · 账目明细', exact:true }).click();
            await page.getByRole('button', { name: '支出', exact: true }).click();
            const grid = page.getByRole('table', { name:'支出明细表', exact:true });
            assert.equal(await page.getByRole('button', { name:'成本规则', exact:true }).count(), 0);
            assert.equal(await page.getByRole('button', { name:'新增一行', exact:true }).count(), 0);
            await grid.waitFor();
            const searchBounds = await page.getByRole('searchbox',{name:'搜索备注或项目'}).boundingBox();
            assert(searchBounds && searchBounds.width >= 100, 'Search must remain visible beside the filter');
            assert.equal(await grid.getByRole('columnheader', { name:'状态', exact:true }).count(), 0);
            const blank = grid.locator('[data-grid-entry="new"]');
            await blank.locator('[tabulator-field="note"]').click();
            await blank.locator('input[aria-label^="项目"]').fill('表格直接录入');
            await blank.locator('[tabulator-field="amount"]').click();
            await blank.locator('input[aria-label^="金额"]').fill('123.45');
            await blank.locator('button').first().click();
            await grid.getByText('表格直接录入', {exact:true}).waitFor();
            let added = db.prepare("SELECT * FROM entries WHERE json_extract(data,'$.note')=?").get('表格直接录入');
            assert.equal(JSON.parse(added.data).amount, 12345);
            const addedRow = grid.locator(`[data-grid-entry="${added.id}"]`);
            await addedRow.getByRole('button', {name:'编辑',exact:true}).click();
            await addedRow.locator('[tabulator-field="amount"]').click();
            const edited = addedRow.locator('input[aria-label^="金额"]');
            await edited.fill('130.25'); await addedRow.locator('button').first().click();
            await page.waitForFunction(id => document.querySelector(`[data-grid-entry="${id}"]`)?.dataset.dirty === 'false', added.id);
            added = db.prepare('SELECT * FROM entries WHERE id=?').get(added.id);
            assert.equal(JSON.parse(added.data).amount, 13025);
            assert.equal(added.version, 2);
            await addedRow.getByRole('button', {name:'编辑',exact:true}).click();
            await addedRow.locator('[tabulator-field="amount"]').click();
            await edited.fill('999'); await addedRow.locator('button').nth(1).click();
            await page.getByRole('heading',{name:'账目明细',exact:true}).click();
            assert.equal(JSON.parse(db.prepare('SELECT data FROM entries WHERE id=?').get(added.id).data).amount, 13025);
            assert.equal(await page.evaluate(() => document.querySelector('[data-rightbar-col]').parentElement.scrollLeft), 0, 'Cell editing must not horizontally scroll the shell');
            await page.getByRole('heading',{name:'账目明细',exact:true}).click();
            await page.screenshot({ path:join(out,'ledger-grid-desktop.png'), fullPage:true });
            await page.setViewportSize({width:390,height:844});
            await page.waitForTimeout(400);
            assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
            await page.screenshot({path:join(out,'ledger-grid-mobile.png'),fullPage:true});
            await page.setViewportSize({width:1440,height:1000});
            await page.reload();
            await page.getByRole('button', { name:'插件规范验收店 · 账目明细', exact:true }).click();
            await page.getByRole('button', {name:'支出',exact:true}).click();
            await page.getByRole('table', {name:'支出明细表'}).getByText('表格直接录入',{exact:true}).waitFor();
            await expandConversations();
            await row().hover();
            await row().click({ button: 'right' });
            await page.getByRole('menuitem', { name: '取消置顶', exact: true }).waitFor();
            await page.getByRole('menuitem', { name: '取消置顶', exact: true }).press('Escape');
            await page.screenshot({path:join(out,'sidebar-hover-desktop.png'),fullPage:true});
            await page.getByRole('table', {name:'支出明细表'}).locator(`[data-grid-entry="${added.id}"]`).getByRole('button',{name:'删除',exact:true}).click();
            await page.getByRole('button',{name:'确认删除',exact:true}).click();
            await page.getByRole('table', {name:'支出明细表'}).getByText('表格直接录入',{exact:true}).waitFor({state:'detached'});
            assert.equal(db.prepare('SELECT status FROM entries WHERE id=?').get(added.id).status, 'void');
            await newChat.click();
            await page.getByRole('heading', { name: '今天，赚了么？', exact: true }).waitFor();
            assert.equal(await page.getByRole('table', { name: '支出明细表', exact: true }).count(), 0);
            assert.equal(await conversationToggle.getAttribute('aria-expanded'), 'true');
            console.log('Collapsed intelligent management, inline new conversation, separate history dialogs, floating menus, persistent pin and spreadsheet add/edit/Escape/reload passed.');

        } finally { db.close(); }
        const unauth = await fetch(new URL('/api/zhuanleme?shop='+result.shop+'&day='+result.day, result.url));
        assert.equal(unauth.status, 401);
        assert.deepEqual(errors, []);
        console.log('Browser passed: inline confirmations, reload, desktop/mobile, archive/unarchive, persistent delete/restore, ledger unchanged, unauthenticated API.');
    } catch (error) {
        if (page) {
            await page.screenshot({ path: join(home, 'browser-failure.png'), fullPage: true });
            await writeFile(join(home, 'browser-failure.txt'), await page.locator('body').innerText());
        }
        throw error;
    } finally { await browser.close(); }
}
