import React, {useEffect,useState} from 'react';
import {Dialog,DialogTitle,DialogContent,DialogActions,Button,Stack,TextField,Alert,Checkbox,FormControlLabel,Typography,Table,TableHead,TableBody,TableRow,TableCell} from '@mui/material';
import * as XLSX from 'xlsx';
import {api} from './model.js';
import {exportText,typeLabel} from './ledger-table-model.mjs';
const money=value=>value==null?'—':(value/100).toFixed(2);
const download=(data,name)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
/** Less frequent ledger workflows stay in the table's More menu. */
export function LedgerManager({kind,shop,day,t,onClose,onSave}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[data,setData]=useState(null),[from,setFrom]=useState(day.slice(0,8)+'01'),[to,setTo]=useState(day),[selected,setSelected]=useState([]),[backup,setBackup]=useState(null),[confirmed,setConfirmed]=useState(false);
 const request=body=>api({shop,...body});
 const run=async fn=>{setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}};
 useEffect(()=>{let active=true;void run(async()=>{
  if(kind==='manageHistory'){const value=await request({op:'history'});if(active)setData({...value,hasMore:value.history.length===100});}
  if(kind==='manageClose'){const value=await fetch('/api/zhuanleme?shop='+encodeURIComponent(shop)+'&day='+day).then(r=>r.json());if(active)setSelected(value.settings?.channels||[]);}
 });return()=>{active=false;};},[kind,shop]);
 const query=async(offset=0)=>{const value=await request({op:'period',from,to,offset,limit:50});setData(value);};
 return <Dialog open onClose={()=>{if(!busy)onClose();}} fullWidth maxWidth="md"><DialogTitle>{t(kind)}</DialogTitle><DialogContent><Stack spacing={2} sx={{pt:1}}>
 {error&&<Alert severity="error">{error}</Alert>}
 {kind==='manageHistory'&&<>{!data?.history?.length&&<Typography>{t('historyEmpty')}</Typography>}<Table size="small"><TableHead><TableRow><TableCell>{t('time')}</TableCell><TableCell>{t('item')}</TableCell><TableCell>{t('action')}</TableCell><TableCell/></TableRow></TableHead><TableBody>{data?.history?.map(row=><TableRow key={row.seq}><TableCell>{new Date(row.created).toLocaleString()}</TableCell><TableCell>{row.note||t('unnamed')}</TableCell><TableCell>{t(row.action==='posted'?'historyAdded':row.action==='void'?'gridDelete':row.action)}</TableCell><TableCell><Button disabled={busy||!row.canUndo} onClick={()=>void run(async()=>{await onSave({op:'undo',...row.undo});const value=await request({op:'history'});setData({...value,hasMore:value.history.length===100});})}>{t(row.action==='void'?'restoreRecord':'gridUndo')}</Button></TableCell></TableRow>)}</TableBody></Table>{data?.hasMore&&<Button disabled={busy} onClick={()=>void run(async()=>{const value=await request({op:'history',before:data.history.at(-1).seq});setData({history:[...data.history,...value.history],hasMore:value.history.length===100});})}>{t('loadOlderHistory')}</Button>}</>}
 {kind==='managePeriod'&&<><Stack direction="row" spacing={1}><TextField disabled={busy} type="date" label={t('fromDate')} value={from} onChange={e=>{setFrom(e.target.value);setData(null);}} InputLabelProps={{shrink:true}}/><TextField disabled={busy} type="date" label={t('toDate')} value={to} onChange={e=>{setTo(e.target.value);setData(null);}} InputLabelProps={{shrink:true}}/><Button disabled={busy} onClick={()=>void run(()=>query())}>{t('query')}</Button></Stack>
 {data?.totals&&<><Typography>{t('knownRevenue')}: {money(data.totals.knownRevenue)} · {t('revenue')}: {money(data.totals.revenue)} · {t('cost')}: {money(data.totals.cost)} · {t('profit')}: {money(data.totals.profit)}</Typography>{!data.totals.revenueComplete&&<Alert severity="info">{t('incomeIncomplete')}</Alert>}
 <Button disabled={busy} onClick={()=>void run(async()=>{let rows=[],offset=0,revision;do{const page=await request({op:'period',from,to,offset,limit:500});if(revision!==undefined&&revision!==page.revision)throw new Error(t('exportChanged'));revision=page.revision;rows.push(...page.entries);offset+=page.entries.length;if(!page.hasMore)break;if(offset>=200000)throw new Error(t('exportTooLarge'));}while(true);const sheet=XLSX.utils.aoa_to_sheet([[t('date'),t('item'),t('gridType'),t('amount')],...rows.map(r=>[[r.day,r.time].filter(Boolean).join(' '),exportText(r.note),typeLabel([r.kind,r.category||r.channel].filter(Boolean).join(':'),t),(r.refundOf?-1:1)*r.amount/100])]);const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,t('entries'));XLSX.writeFile(book,from+'_'+to+'.xlsx');})}>{t('gridExportExcel')}</Button>
 <Table size="small"><TableBody>{data.entries.map(row=><TableRow key={row.id}><TableCell>{row.day} {row.time}</TableCell><TableCell>{row.note||t('unnamed')}</TableCell><TableCell align="right">{money((row.refundOf?-1:1)*row.amount)}</TableCell></TableRow>)}</TableBody></Table><Stack direction="row"><Button disabled={busy||!data.offset} onClick={()=>void run(()=>query(Math.max(0,data.offset-50)))}>{t('previousPage')}</Button><Typography>{data.total} {t('records')}</Typography><Button disabled={busy||!data.hasMore} onClick={()=>void run(()=>query(data.offset+50))}>{t('nextPage')}</Button></Stack></>}</>}
 {kind==='manageClose'&&<><Typography>{t('closeDayHint')}</Typography>{['store','meituan','douyin','other'].map(c=><FormControlLabel key={c} control={<Checkbox checked={selected.includes(c)} onChange={e=>{setConfirmed(false);setSelected(e.target.checked?[...selected,c]:selected.filter(x=>x!==c));}}/>} label={t(c)}/>)}<FormControlLabel control={<Checkbox checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>} label={t('closeDayConfirm')}/><Button disabled={busy||!confirmed||!selected.length} onClick={()=>void run(async()=>{await onSave({op:'settings',channels:selected});await onSave({op:'close-day',day,channels:selected});onClose();})}>{t('closeDay')}</Button></>}
 {kind==='manageBackup'&&<><Typography>{t('backupHint')}</Typography><Button disabled={busy} onClick={()=>void run(async()=>download(await request({op:'backup'}),'ledger-'+day+'.json'))}>{t('backupDownload')}</Button><Button component="label" disabled={busy}>{t('backupChoose')}<input hidden type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{setBackup(null);setData(null);if(file.size>30*1024*1024)throw new Error(t('backupTooLarge'));const value=JSON.parse(await file.text());const preview=await request({op:'backup-preview',backup:value});setBackup(value);setData(preview);});e.target.value='';}}/></Button>{backup&&<><Typography>{data?.entries} {t('records')} · {data?.audit} {t('historyCount')} · {data?.created}</Typography><Alert severity="info">{t('restoreHint')}</Alert><Button disabled={busy} onClick={()=>void run(async()=>{await onSave({op:'restore',backup,checksum:data.checksum});onClose();})}>{t('restoreConfirm')}</Button></>}</>}
 </Stack></DialogContent><DialogActions><Button disabled={busy} onClick={onClose}>{t('close')}</Button></DialogActions></Dialog>;
}
