export const zh = { brand: '赚了么', welcome: '今天，赚了么？', shops: '我的店铺', addShop: '添加店铺', shopName: '店铺名字', shopPlaceholder: '例如：文昌路总店', create: '创建店铺', cancel: '取消', newChat: '新建对话', open: '打开', ledger: '经营账表', chat: 'AI 对话', manual: '手动录入', rules: '成本规则', overview: '经营总览', entries: '账目明细', date: '营业日期', revenue: '营业收入', cost: '经营成本', profit: '预计利润', actualProfit: '经营利润', missing: '待补全', zero: '暂无记录', trend: '近七天经营趋势', breakdown: '利润成本表', item: '项目', basis: '计算依据', amount: '金额（元）', action: '操作', materials: '商品成本', labor: '人工', rent: '房租', utilities: '水电燃气', platform: '平台费用', other: '其他', store: '线下门店', meituan: '即时零售', douyin: '抖音', all: '全店营业额', purchase: '采购支出', actual: '实际成本', kind: '录入类型', channel: '收入渠道', category: '成本项目', note: '备注', save: '保存入账', saving: '保存中…', edit: '修改', void: '撤销', confirmVoid: '确认撤销', keep: '保留', confirm: '确认入账', drafts: 'AI 待核对草稿', draftHint: '核对日期、金额和归属后确认，草稿尚未计入利润。', posted: '已入账', draft: '待核对', voided: '已撤销', source: '来源', manualSource: '手动', aiSource: 'AI 草稿', empty: '这家店的账，从第一笔开始', emptyHint: '手动记录营业收入，或在右侧告诉经营助手。账目保存后，趋势与利润会同步更新。', pickShop: '先选择或添加一家店铺', pickHint: '每家店拥有独立账本，多次对话共用同一本账。', costHint: '缺少的项目不会按零计算。确实没有的费用，请在成本规则中明确填 0。', purchaseHint: '采购记录保留在账目明细，不直接扣减当天利润。', actualHint: '填写该日该项目的完整实际成本，将替换同范围估算，不重复相加。', revenueHint: '填写该日该渠道的完整营业额；同渠道已有记录时，请修改原记录。', rulesHint: '按生效日期保存新版本。月固定金额按当月实际天数分摊；实际成本优先。', monthly: '月固定金额', daily: '日固定金额', percent: '营业额比例 %', effective: '生效日期', method: '计算方法', base: '计费基数', value: '金额 / 比例', saveRules: '保存成本规则', actualBasis: '实际记录', missingBasis: '尚未填写', monthlyBasis: '月金额按自然日分摊', dailyBasis: '每日固定', percentBasis: '按营业额比例估算', total: '合计', known: '已知成本', loading: '正在读取账本…', retry: '重新读取', saved: '已保存', failed: '操作失败', noEntries: '所选日期还没有账目', status: '状态', money: '元', sevenDays: '营业收入、成本与利润；缺失日期不连线', shopCreating: '正在创建…', changeHint: '保存后保留修改记录，可在账目明细撤销。', rulesRequired: '请填写全部成本项目；无该项费用请明确填 0。', chatHint: '可以说：记一笔今天的采购，牛肉 860 元。', errorShop: '店铺操作失败', close: '关闭', purchaseTotal: '采购合计（不直接扣利润）' };
Object.assign(zh, { home: '店铺首页', assistant: '经营助手', openOverview: '查看经营总览', openEntries: '查看账目明细', openChat: '与 AI 协作', homeTitle: '把店铺经营，看得更清楚。', homeHint: '从一笔记录到一份经营判断，账表与助手协同工作。', homeGuide: '选择经营总览或账目明细，即可一边看数据，一边与 AI 讨论。', demo: '演示数据', demoHint: '此店为虚拟零售店，数据仅供体验，与其他店铺账本独立。', loadDemo: '体验演示店', costStructure: '成本构成', share: '占比', partialCost: '已知成本占比', noCost: '尚无可展示的成本', details: '成本依据', closePanel: '收起面板', records: '条记录', search: '搜索备注或项目', filter: '账目类型', allEntries: '全部类型', unit: '单位：元', receipt: '记录', allShops: '选择店铺', homeNoShop: '让每一笔经营，都有据可循。', chatHint: '可以说：记一笔今天的采购，咖啡豆 860 元。', trend: '近七天收支', sevenDays: '近七天流水与成本同柱叠加，利润为折线；缺失利润不连线', selectedDay: '查看这一天', homeReady: '店铺账本持续保存，切换对话也不会丢失。' });
Object.assign(zh, { pendingChanges: 'AI 待核对修改', pendingHint: '核对修改前后内容。确认后生效；原记录已变化时，需重新生成建议。', beforeChange: '修改前', afterChange: '修改后', applyChange: '确认修改', rejectChange: '放弃修改' });
export const en = { ...zh, brand: '赚了么', welcome: '今天，赚了么？', shops: 'Shops', addShop: 'Add shop', ledger: 'Ledger', chat: 'AI chat', manual: 'Manual entry', rules: 'Cost rules', save: 'Save entry', cancel: 'Cancel', revenue: 'Revenue', cost: 'Operating cost', profit: 'Estimated profit', missing: 'Incomplete', newChat: 'New conversation' };
Object.assign(en, { pendingChanges: 'AI changes for review', pendingHint: 'Review the changes before applying. If the original has changed, generate a new proposal.', beforeChange: 'Before', afterChange: 'After', applyChange: 'Apply changes', rejectChange: 'Discard changes' });

Object.assign(zh, { reviewTitle: '入账确认卡片', reviewEntry: '核对入账', reviewChange: '核对账目修改', reviewRules: '核对成本规则', reviewLoading: '正在读取当前状态…', reviewGenerating: '正在生成…', reviewUnavailable: '查看工具结果', reviewInvalid: '无法读取核对内容，请重新生成建议。', reviewRecheck: '请核对当前内容后再操作。', reviewHint: '请核对以上内容，确认后立即生效。', reviewDiscard: '放弃', reviewDiscarded: '已放弃', reviewApplied: '已生效' });
Object.assign(en, { reviewTitle: 'Ledger confirmation', reviewEntry: 'Review entry', reviewChange: 'Review entry changes', reviewRules: 'Review cost rules', reviewLoading: 'Loading current status…', reviewGenerating: 'Generating…', reviewUnavailable: 'View tool result', reviewInvalid: 'Unable to read this item. Please generate a new proposal.', reviewRecheck: 'Review the current details before trying again.', reviewHint: 'Review these details. Confirmation takes effect immediately.', reviewDiscard: 'Discard', reviewDiscarded: 'Discarded', reviewApplied: 'Applied' });

Object.assign(zh, { gridTitle: '经营记账表', gridType: '类型 / 归属', gridHint: '直接编辑单元格；Tab 切换，Enter 或离开本行保存，Esc 取消。最后一行可新增记录。', gridNewProject: '输入项目，新增一笔记录', gridRequired: '请填写日期和金额。', gridAmountError: '金额须为非负数，最多两位小数。', gridRetry: '重试保存', gridDiscard: '放弃本行修改', manual: '新增一行' });
Object.assign(en, { gridTitle: 'Business ledger', gridType: 'Type / scope', gridHint: 'Edit cells directly. Tab moves between cells; Enter or leaving the row saves; Esc cancels. Add entries in the final row.', gridNewProject: 'Enter an item to add a record', gridRequired: 'Enter the date and amount.', gridAmountError: 'Use a nonnegative amount with up to two decimals.', gridRetry: 'Retry save', gridDiscard: 'Discard row changes', manual: 'Add row' });

Object.assign(zh, { gridSwitch: '收支切换', gridIncome: '收入', gridExpenses: '支出', gridIncomeTable: '收入明细表', gridExpenseTable: '支出明细表', gridEdit: '编辑', gridSave: '保存', gridDelete: '删除', gridConfirmDelete: '确认删除' });
Object.assign(en, { gridSwitch: 'Income and expenses', gridIncome: 'Income', gridExpenses: 'Expenses', gridIncomeTable: 'Income entries', gridExpenseTable: 'Expense entries', gridEdit: 'Edit', gridSave: 'Save', gridDelete: 'Delete', gridConfirmDelete: 'Confirm delete' });

Object.assign(zh, { gridExport: '导出账目', gridExportExcel: '导出 Excel', gridExportCSV: '导出 CSV' });
Object.assign(en, { gridExport: 'Export entries', gridExportExcel: 'Export Excel', gridExportCSV: 'Export CSV' });

Object.assign(zh, { gridAddRecord: '新增账目', gridAddIncome: '新增收入', gridAddExpense: '新增支出', gridEditRecord: '编辑账目', gridDeleteRecord: '删除这笔账目？', gridExportSelected: '导出选中记录 · Excel' });
Object.assign(en, { gridAddRecord: 'New entry', gridAddIncome: 'New income', gridAddExpense: 'New expense', gridEditRecord: 'Edit entry', gridDeleteRecord: 'Delete this entry?', gridExportSelected: 'Export selected · Excel' });
Object.assign(zh, { gridUndo: '撤销上一步', gridMore: '更多表格操作', gridFilters: '显示／隐藏筛选', gridDensity: '切换紧凑间距', gridFullscreen: '切换全屏', gridShowDate: '显示日期列', gridHideDate: '隐藏日期列', gridAddRecord: '新增' });
Object.assign(en, { gridUndo: 'Undo last action', gridMore: 'More table actions', gridFilters: 'Toggle filters', gridDensity: 'Toggle compact spacing', gridFullscreen: 'Toggle full screen', gridShowDate: 'Show date column', gridHideDate: 'Hide date column', gridAddRecord: 'New' });

Object.assign(zh, {time:'发生时间', manageHistory:'修改历史与恢复',managePeriod:'期间报表与导出',manageClose:'收入核对与日结',manageBackup:'账本备份与恢复',historyEmpty:'暂无可恢复记录',unnamed:'未命名项目',restoreRecord:'恢复',fromDate:'开始日期',toDate:'结束日期',query:'查询',previousPage:'上一页',nextPage:'下一页',records:'笔记录',closeDay:'确认日结',closeDayHint:'选择店铺启用的收入渠道。请逐项核对当天全部收入；没有收入的已启用渠道也需要明确确认为零。',closeDayConfirm:'我已核对所选渠道的全部收入，未录入的所选渠道当天收入确实为零',backupHint:'备份包含当前店铺账目、规则、建议、修改历史和日结状态；聊天记录由 DSH 单独保存，不包含在此文件中。',backupDownload:'下载账本备份',backupChoose:'选择备份文件',backupTooLarge:'备份文件不能超过 30 MB',historyCount:'条历史',restoreHint:'仅支持恢复到新建的空店铺，避免覆盖现有数据。请先在侧栏新建店铺，再在该店恢复。',restoreConfirm:'确认恢复到当前空店铺',incomeIncomplete:'收入尚未完成日结核对，当前数据和利润可能不完整。',draftStorageError:'浏览器未能保留草稿，请勿离开页面。',resumeDraft:'继续未保存的录入',unsavedEdit:'有一项修改尚未保存，可重试或取消。',transactionHint:'这是逐笔记录，同类逐笔金额累计；不会与已有日汇总重复混记。'});
Object.assign(en, {time:'Time',manageHistory:'History and recovery',managePeriod:'Period report and export',manageClose:'Revenue reconciliation',manageBackup:'Ledger backup and restore',historyEmpty:'No recoverable operations',unnamed:'Untitled',restoreRecord:'Restore',fromDate:'From',toDate:'To',query:'Query',previousPage:'Previous',nextPage:'Next',records:'records',closeDay:'Close day',closeDayHint:'Select enabled channels and verify every receipt; explicitly confirm zero-income channels.',closeDayConfirm:'All selected channels are complete; selected channels without entries had zero revenue.',backupHint:'Includes ledger entries, rules, proposals, audit and day closures. DSH chat transcripts are separate.',backupDownload:'Download backup',backupChoose:'Choose backup',backupTooLarge:'Backup exceeds 30 MB',historyCount:'audit records',restoreHint:'Restore only into a new, empty shop to protect existing data.',restoreConfirm:'Restore into current empty shop',incomeIncomplete:'Revenue has not been reconciled; figures and profit may be incomplete.',draftStorageError:'Draft could not be saved locally. Keep this page open.',resumeDraft:'Continue unsaved entry',unsavedEdit:'An edit is unsaved. Retry or cancel.',transactionHint:'This is an individual transaction. Transactions accumulate and cannot mix with daily summaries.'});
Object.assign(zh,{refundOf:'退款原记录 ID',settlement:'收付款状态',settlement_unknown:'未确认',settlement_pending:'待收付',settlement_paid:'已收付',account:'账户',entryMode:'记账口径',transaction:'逐笔',summary:'日汇总',extraFields:'显示／隐藏业务字段'});
Object.assign(en,{refundOf:'Original entry ID',settlement:'Payment status',settlement_unknown:'Unknown',settlement_pending:'Pending',settlement_paid:'Paid',account:'Account',entryMode:'Entry mode',transaction:'Transaction',summary:'Daily summary',extraFields:'Show / hide business fields'});
Object.assign(zh,{notRefund:'普通账目',refund:'退款',historyAdded:'新增入账',confirm:'确认入账'});
Object.assign(en,{notRefund:'Regular entry',refund:'Refund'});
Object.assign(zh,{exportChanged:'导出期间账本发生了变化，请重新导出以保持数据一致。'});
Object.assign(en,{exportChanged:'The ledger changed during export. Please export again for a consistent result.'});

Object.assign(zh,{historyAdded:"新增入账",knownRevenue:"已记录净收入",exportTooLarge:"记录超过单次导出上限，请缩短日期范围。",pagination:"表格分页",page:"第",firstPage:"第一页",lastPage:"最后一页"});
Object.assign(en,{historyAdded:"Entry added",knownRevenue:"Recorded net revenue",exportTooLarge:"Too many records. Use a shorter date range.",pagination:"Table pagination",page:"Page",firstPage:"First page",lastPage:"Last page"});

Object.assign(zh,{loadOlderHistory:'更早的修改记录'});
Object.assign(en,{loadOlderHistory:'Older changes'});

Object.assign(zh,{date:'日期',dateTime:'日期',dateTimeError:'请输入有效日期，例如 2026-09-22 或 2026-09-22 11:45。'});
Object.assign(en,{date:'Date',dateTime:'Date',dateTimeError:'Enter a valid date, e.g. 2026-09-22 or 2026-09-22 11:45.'});

Object.assign(zh,{trend:'经营趋势',trendScroll:'左右滚动查看日期，点击查看当天数据',olderDates:'更早日期',sevenDays:'按日期排列的收入、成本与利润趋势'});
Object.assign(en,{trend:'Business trend',trendScroll:'Scroll through dates; select a day to view its figures',olderDates:'Earlier dates',sevenDays:'Revenue, cost and profit by date'});

Object.assign(zh,{trendScroll:'按住鼠标左右拖动查看日期，每屏七天；点击查看当天数据'});
Object.assign(en,{trendScroll:'Drag to browse seven days at a time; select a day to view its figures'});

Object.assign(zh,{deleteShop:'删除店铺',deleteShopHint:'从列表移除，账本与对话保留，可在已删除店铺中恢复。',deletedShops:'已删除店铺',restoreShop:'恢复',voiceStart:'语音输入',voiceStop:'结束录音',voiceWorking:'正在识别…',voiceUnsupported:'当前浏览器不支持录音，请使用 HTTPS 或本机浏览器。',voicePermission:'未获得麦克风权限，请允许后重试。',voiceFailed:'录音失败，请重试。',voiceTooLarge:'录音超过 10MB，请缩短后重试。'});
Object.assign(en,{deleteShop:'Delete shop',deleteShopHint:'Remove from the list. Ledger and chats are retained and can be restored.',deletedShops:'Deleted shops',restoreShop:'Restore',voiceStart:'Voice input',voiceStop:'Stop recording',voiceWorking:'Transcribing…',voiceUnsupported:'Recording requires a supported browser on HTTPS or localhost.',voicePermission:'Microphone permission was denied. Allow access and retry.',voiceFailed:'Recording failed. Please retry.',voiceTooLarge:'Recording exceeds 10MB. Try a shorter recording.'});

Object.assign(zh,{confirmDeleteShop:'确认删除店铺？',shopDeleting:'正在删除…'});
Object.assign(en,{confirmDeleteShop:'Delete this shop?',shopDeleting:'Deleting…'});

Object.assign(zh,{voiceCancel:'取消本次录音',voiceSend:'结束录音并发送',voiceRecording:'正在录音，文字实时显示在输入框',voicePreparing:'正在连接麦克风…',voiceDisconnected:'麦克风已断开，已保留识别文字，请重新连接。',voiceSlow:'识别连接较慢，已停止录音并保留文字，请重试。'});
Object.assign(en,{voiceCancel:'Cancel recording',voiceSend:'Stop recording and send',voiceRecording:'Recording; live text appears in the composer',voicePreparing:'Connecting microphone…',voiceDisconnected:'Microphone disconnected. Recognized text was kept. Reconnect and retry.',voiceSlow:'Recognition is too slow. Recording stopped and your text was kept. Please retry.'});
